### eqmake4 was here ###
CONFIG -= debug_and_release debug
CONFIG += release

######################################################################
# Automatically generated by qmake (1.07a) Wed Sep 1 15:54:18 2004
######################################################################

TEMPLATE = app
CONFIG += console

SOURCES += example.cpp

include(../src/qtlockedfile.pri)
